### ISSUE TITLE
rename repo -> geth-ipc-reverse-proxy-with-whitelist

### ISSUE THREAD

**Issue by meowsbits** [ETCCooperative/jsonrpc-gatekeeper#1]
Proposing a rename that signals this is a reverse proxy that implements a JSONRPC method whitelist for _geth's_ JSONRPC IPC API, as opposed to some generic JSONRPC API middleware.

Definitely open to suggestions on the name.

**Comment by ziogaschr** [comment]
Fine with me, I would suggest keeping the IPC out, as I am thinking to add support for WS transfer as well. Also, @diega was thinking to use the same on besu.

Suggested name: `clients-reverse-proxy-with-whitelist`

**Comment by diega** [comment]
I don't have a strong opinion on this. I could say that `jsonrpc-gateway` could work too. _jsonrpc_ is the protocol and _gateway_ is what we are opening with whatever policy we want

**Comment by meowsbits** [comment]
What about `jsonrpc-gatekeeper`, since its _raison d'etre_ is permissioning certain methods? (And `jsonrpc-police` is just too weird :joy_cat:) 

Or `jsonrpc-policy-proxy`? I'm good with `-gateway` too, IMO its suggestive enough.

**Comment by ziogaschr** [comment]
`jsonrpc-gatekeeper` I think I liked this one

**Comment by diega** [comment]
Yeah, me too

**Comment by ziogaschr** [comment]
Repo name done. I will update README and package.json tomorrow

**Comment by ziogaschr** [comment]
Done with https://github.com/ETCCooperative/jsonrpc-gatekeeper/commit/9f669966bfde4f4c876a9a42b851f0e21399cb8d
